apiVersion: v1
kind: ConfigMap
metadata:
  name: movieticket-config
  namespace: movieticket
data:
  NODE_ENV: "production"
  PORT: "3000"
  JWT_EXPIRE: "7d"
  CORS_ORIGIN: "http://localhost:8080"
  MONGODB_URI: "mongodb://movieticket-mongo:27017/movieticket"

