apiVersion: v1
kind: Service
metadata:
  name: movieticket-api
  namespace: movieticket
  labels:
    app: movieticket-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: movieticket-api
---
apiVersion: v1
kind: Service
metadata:
  name: movieticket-frontend
  namespace: movieticket
  labels:
    app: movieticket-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: movieticket-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: movieticket-mongo
  namespace: movieticket
  labels:
    app: movieticket-mongo
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: movieticket-mongo
  clusterIP: None  # Headless service for StatefulSet

